name: Continuous Integration
 
on: 
  pull_request:
    branches:
      - master
 
jobs:
  test:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        node-version: '18'
 
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install migrate and test
      run: |
        npm install
        npm run migrate up
        npm run test
      env:
        CI: true
        PGHOST_TEST: ${{ secrets.PGHOST }}
        PGUSER_TEST: ${{ secrets.PGUSER }}
        PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
        PGPASSWORD_TEST: ${{ secrets.PGPASSWORD }}
        PGPORT_TEST: ${{ secrets.PGPORT }}
        PGHOST: ${{ secrets.PGHOST }}
        PGUSER: ${{ secrets.PGUSER }}
        PGDATABASE: ${{ secrets.PGDATABASE }}
        PGPASSWORD: ${{ secrets.PGPASSWORD }}
        PGPORT: ${{ secrets.PGPORT }}
        ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
        ACCCESS_TOKEN_AGE: ${{ secrets.ACCCESS_TOKEN_AGE }}